//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giorni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giorni()
        {
            this.giorniCommesse = new HashSet<giorniCommesse>();
        }
    
        public int id { get; set; }
        public Nullable<int> TipoOre { get; set; }
        public Nullable<int> ore { get; set; }
        public Nullable<System.DateTime> giorno { get; set; }
        public Nullable<int> idUtenti { get; set; }
    
        public virtual TipologiaOre TipologiaOre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giorniCommesse> giorniCommesse { get; set; }
    }
}
