//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class giorniCommesse
    {
        public int id { get; set; }
        public Nullable<int> idGiorno { get; set; }
        public Nullable<int> idCommessa { get; set; }
    
        public virtual Commesse Commesse { get; set; }
        public virtual Giorni Giorni { get; set; }
    }
}
